spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.0.129:3306/activiti7-imooc?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true