spring:
  datasource:
    username: root
    password: 12345678
    url: jdbc:mysql://localhost:3306/activiti7-imooc?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true